### ISSUE TITLE
Добрый день. У меня есть ключ эцп и пароль, как мне подписать файл, подскажи пожалуйста алгоритм дейсвий, какие функции вызывать и в каком порядке?

### ISSUE THREAD

**Issue by lnnd** [leon-mbs/DSTUSign#1]

**Comment by leon-mbs** [comment]
в  том  же порядке   что в  примере

**Comment by lnnd** [comment]
У меня нет сертификата, я не могу прочитать сертификат var cert = new Cert(File.ReadAllBytes("cert.cer"));

**Comment by leon-mbs** [comment]
если  нет сертификата  то  какого  чуда  вы  хотите

**Comment by leon-mbs** [comment]
есть  какой  то там  сайт в  АЦСК где  можно  получить сертификат  по  ключу

**Comment by lnnd** [comment]
Есть на Си плюсах библиотеки где используется только Ключ и пароль. Возможно используется OCSP сервис для получения сертификата. Сам я не специалист, пытаюсь разобраться

**Comment by leon-mbs** [comment]
наверно  используется
в  этой  библиотеке  этого нет
раз  в  году  сертификат  можно и вручную  скачать

**Comment by lnnd** [comment]
Зрозумів, дякую
